[package]
name = "stwo-metal-standalone-upstream-dev-poly"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = []

[dependencies]
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
stwo = { git = "https://github.com/starkware-libs/stwo.git", rev = "62b228ed4a30ef96715e201c4c6e0742aa8bbd42", package = "stwo", default-features = false, features = ["prover"] }
stwo-metal = { path = "../../crates/stwo-metal", default-features = false, features = ["prover"] }

[patch."https://github.com/starkware-libs/stwo.git"]
stwo = { path = "../../vendor/stwo-upstream-dev-62b228e/crates/stwo" }

[patch."https://github.com/AntChainOpenLabs/NitrooZK-stwo.git"]
stwo = { path = "../../vendor/stwo-upstream-dev-62b228e/crates/stwo" }
